//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergi.Licensing.Web.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synergi.Licensing.Web.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked out because of a maximum number of incorrect login attempts. You will NOT be able to login until you contact a site administrator and have your account unlocked..
        /// </summary>
        internal static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not yet been approved by the site&apos;s administrators. Please try again later....
        /// </summary>
        internal static string AccountNotApproved {
            get {
                return ResourceManager.GetString("AccountNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SynergiLicensing.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete due to dependencies.
        /// </summary>
        internal static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created .
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error with the date range entered.
        /// </summary>
        internal static string DateValidatorInvalid {
            get {
                return ResourceManager.GetString("DateValidatorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of entries reached (12).
        /// </summary>
        internal static string DateValidatorMax {
            get {
                return ResourceManager.GetString("DateValidatorMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin@Admin.com.
        /// </summary>
        internal static string DefaultAdminEmail {
            get {
                return ResourceManager.GetString("DefaultAdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.
        /// </summary>
        internal static string DefaultLoading {
            get {
                return ResourceManager.GetString("DefaultLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultPage {
            get {
                return ResourceManager.GetString("DefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00.
        /// </summary>
        internal static string DefaultTime {
            get {
                return ResourceManager.GetString("DefaultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\Images\grid-delete.gif.
        /// </summary>
        internal static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\Images\grid-delete-disabled.gif.
        /// </summary>
        internal static string DeleteImageDisabled {
            get {
                return ResourceManager.GetString("DeleteImageDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1.
        /// </summary>
        internal static string HashMethod {
            get {
                return ResourceManager.GetString("HashMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , last updated .
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading information has been saved.
        /// </summary>
        internal static string LoadingSaved {
            get {
                return ResourceManager.GetString("LoadingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleList.xml.
        /// </summary>
        internal static string ModuleFileName {
            get {
                return ResourceManager.GetString("ModuleFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record..
        /// </summary>
        internal static string NewRecord {
            get {
                return ResourceManager.GetString("NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeClock.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete user account please contact your Administrator..
        /// </summary>
        internal static string UnableToDelete {
            get {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was locked out on .
        /// </summary>
        internal static string UnlockAccount {
            get {
                return ResourceManager.GetString("UnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Account.
        /// </summary>
        internal static string UnlockAccountBasic {
            get {
                return ResourceManager.GetString("UnlockAccountBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Please uncheck box, and press Save to unlock account..
        /// </summary>
        internal static string UnlockAccountExtra {
            get {
                return ResourceManager.GetString("UnlockAccountExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on .
        /// </summary>
        internal static string UpdatedOn {
            get {
                return ResourceManager.GetString("UpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested loading update has completed..
        /// </summary>
        internal static string UpdateLoadingComplete {
            get {
                return ResourceManager.GetString("UpdateLoadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that depending on criteria selected this process can take a while to complete..
        /// </summary>
        internal static string UpdateLoadingWarning {
            get {
                return ResourceManager.GetString("UpdateLoadingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user in the database with the username .
        /// </summary>
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
    }
}
